/* ==========================================================================
   UNIPATH - AUSTRALIA SPECIALIZED UNIVERSITY & SCHOLARSHIP DATABASE
   ========================================================================== */

window.UniData = {
  australiaInfo: {
    title: "Study in Oceania Portal",
    subtitle: "Top Universities & Language Institutes in Australia and New Zealand",
    visaType: "Subclass 500 Student Visa",
    healthCover: "OSHC (Overseas Student Health Cover) Required",
    intakes: ["Semester 1 (Feb/March Start)", "Semester 2 (July Start)", "Term 1/2/3 (UNSW 3+ Trimester)"]
  },

  universities: [
    {
      id: "unimelb",
      name: "The University of Melbourne",
      shortName: "UniMelb",
      country: "Australia",
      state: "Victoria",
      city: "Melbourne, VIC",
      cricos: "00116K",
      institutionType: "University",
      isGo8: true,
      worldRank: 14,
      acceptanceRate: 70.0,
      minGpa: 3.5,
      minSat: 1350,
      minIelts: 6.5,
      minPte: 58,
      atarEquivalent: 85,
      tuitionAud: 47500,
      tuitionUsd: 31000,
      image: "assets/images/hero_australia.png",
      tags: ["Group of Eight (Go8)", "Rank #1 in Australia", "Melbourne Model", "CRICOS: 00116K"],
      programs: ["Bachelor of Science (CS)", "Bachelor of Commerce", "Bachelor of Design", "Biomedicine", "Data Science"],
      sem1Deadline: "2026-11-30",
      sem2Deadline: "2026-05-31",
      requirements: [
        "VCE / ATAR or Equivalent International Qualification (IB, A-Levels, AP)",
        "Proof of English (IELTS 6.5+ / PTE 58+ / TOEFL iBT 79+)",
        "Genuine Student (GS) Statement for Visa Subclass 500",
        "Overseas Student Health Cover (OSHC) Certification",
        "Official High School Academic Transcripts",
        "Financial Support Proof (AUD $29,710/yr living costs standard)"
      ],
      description: "Ranked #1 in Australia, Melbourne University is renowned for the 'Melbourne Model' undergraduate structure, vibrant Parkville campus, world-leading research institutes, and exceptional graduate employability."
    },
    {
      id: "usyd",
      name: "The University of Sydney",
      shortName: "USYD",
      country: "Australia",
      state: "New South Wales",
      city: "Sydney, NSW",
      cricos: "00026A",
      institutionType: "University",
      isGo8: true,
      worldRank: 18,
      acceptanceRate: 68.0,
      minGpa: 3.45,
      minSat: 1320,
      minIelts: 6.5,
      minPte: 61,
      atarEquivalent: 83,
      tuitionAud: 48500,
      tuitionUsd: 31800,
      image: "assets/images/campus_sydney.png",
      tags: ["Group of Eight (Go8)", "Iconic Sandstone Campus", "Sydney Quadrangle", "CRICOS: 00026A"],
      programs: ["Bachelor of Advanced Computing", "Bachelor of Commerce", "Medicine & Health", "Architecture", "Law"],
      sem1Deadline: "2026-12-15",
      sem2Deadline: "2026-06-15",
      requirements: [
        "High School Graduation with ATAR or international equivalent",
        "IELTS Academic minimum 6.5 overall (no band lower than 6.0)",
        "Subclass 500 Genuine Student criteria verification",
        "OSHC Provider Enrollment",
        "Passport copy & Financial Capability declaration"
      ],
      description: "Australia's first university, USYD features the world-famous Quadrangle building, strong industry partnerships in Sydney's CBD, and extensive global exchange opportunities."
    },
    {
      id: "unsw",
      name: "UNSW Sydney (University of New South Wales)",
      shortName: "UNSW",
      country: "Australia",
      state: "New South Wales",
      city: "Sydney, NSW",
      cricos: "00098G",
      institutionType: "University",
      isGo8: true,
      worldRank: 19,
      acceptanceRate: 65.0,
      minGpa: 3.4,
      minSat: 1300,
      minIelts: 6.5,
      minPte: 64,
      atarEquivalent: 84,
      tuitionAud: 49000,
      tuitionUsd: 32000,
      image: "assets/images/hero_australia.png",
      tags: ["Group of Eight (Go8)", "Engineering Titan", "UNSW 3+ Trimester", "CRICOS: 00098G"],
      programs: ["Computer Science (AI Specialisation)", "Quantum Engineering", "Finance & Fintech", "Photovoltaics"],
      sem1Deadline: "2026-11-30",
      sem2Deadline: "2026-05-30",
      requirements: [
        "ATAR minimums or SAT/IB scores",
        "English Language test (IELTS 6.5+ or PTE 64+)",
        "Genuine Student (GS) assessment form",
        "OSHC Health Insurance",
        "Academic Reference & CV (for research/honours)"
      ],
      description: "UNSW Sydney is a powerhouse for engineering, solar energy research, tech entrepreneurship, and computer science, operating under the flexible UNSW 3+ trimester model."
    },
    {
      id: "anu",
      name: "Australian National University",
      shortName: "ANU",
      country: "Australia",
      state: "Australian Capital Territory",
      city: "Canberra, ACT",
      cricos: "00120C",
      institutionType: "University",
      isGo8: true,
      worldRank: 30,
      acceptanceRate: 60.0,
      minGpa: 3.5,
      minSat: 1340,
      minIelts: 6.5,
      minPte: 64,
      atarEquivalent: 82,
      tuitionAud: 45000,
      tuitionUsd: 29500,
      image: "assets/images/campus_sydney.png",
      tags: ["Group of Eight (Go8)", "National Capital Uni", "Policy & Cyber", "CRICOS: 00120C"],
      programs: ["Advanced Computing (R&D)", "International Relations", "Cyber Security", "Physics & Astronomy"],
      sem1Deadline: "2026-12-01",
      sem2Deadline: "2026-05-15",
      requirements: [
        "ATAR or equivalent (e.g., SAT 1340+ / IB 31+)",
        "IELTS Academic 6.5 (min 6.0 in each module)",
        "Genuine Student (GS) statement",
        "Proof of financial capacity for Subclass 500 visa"
      ],
      description: "Located in Australia's capital Canberra, ANU is the national research university closely aligned with federal science agencies, national security centers, and global diplomacy."
    },
    {
      id: "uq",
      name: "The University of Queensland",
      shortName: "UQ",
      country: "Australia",
      state: "Queensland",
      city: "Brisbane, QLD",
      cricos: "00025B",
      institutionType: "University",
      isGo8: true,
      worldRank: 40,
      acceptanceRate: 72.0,
      minGpa: 3.3,
      minSat: 1280,
      minIelts: 6.5,
      minPte: 64,
      atarEquivalent: 78,
      tuitionAud: 44000,
      tuitionUsd: 28800,
      image: "assets/images/hero_australia.png",
      tags: ["Group of Eight (Go8)", "Subtropical St Lucia Campus", "Biotech Leadership", "CRICOS: 00025B"],
      programs: ["Software Engineering", "Biotechnology", "Environmental Management", "Marine Science"],
      sem1Deadline: "2026-11-30",
      sem2Deadline: "2026-05-31",
      requirements: [
        "High school diploma / ATAR threshold",
        "IELTS 6.5 overall (no band below 6.0)",
        "OSHC Health Insurance setup",
        "Subclass 500 Student Visa compliance"
      ],
      description: "UQ boasts a stunning campus along the Brisbane River in sunny Queensland, recognized globally for vaccine development, bioengineering, and clean technology."
    },
    {
      id: "monash",
      name: "Monash University",
      shortName: "Monash",
      country: "Australia",
      state: "Victoria",
      city: "Melbourne, VIC",
      cricos: "00008C",
      institutionType: "University",
      isGo8: true,
      worldRank: 42,
      acceptanceRate: 75.0,
      minGpa: 3.25,
      minSat: 1260,
      minIelts: 6.5,
      minPte: 58,
      atarEquivalent: 75,
      tuitionAud: 43500,
      tuitionUsd: 28500,
      image: "assets/images/campus_sydney.png",
      tags: ["Group of Eight (Go8)", "Pharmacy & CS Leader", "Global Campuses", "CRICOS: 00008C"],
      programs: ["Computer Science", "Pharmacy & Pharmaceutical Sciences", "Banking & Finance", "Robotics"],
      sem1Deadline: "2026-12-01",
      sem2Deadline: "2026-06-01",
      requirements: [
        "ATAR 75+ or equivalent IB/SAT qualification",
        "IELTS 6.5 or PTE Academic 58",
        "Subclass 500 Visa documentation & GS letter"
      ],
      description: "Australia's largest university, Monash is celebrated for world #2 rankings in Pharmacy, cutting-edge AI labs, and expansive global alliance programs."
    },
    {
      id: "uts",
      name: "University of Technology Sydney",
      shortName: "UTS",
      country: "Australia",
      state: "New South Wales",
      city: "Sydney, NSW",
      cricos: "00099F",
      institutionType: "University",
      isGo8: false,
      worldRank: 88,
      acceptanceRate: 78.0,
      minGpa: 3.1,
      minSat: 1220,
      minIelts: 6.5,
      minPte: 58,
      atarEquivalent: 72,
      tuitionAud: 41000,
      tuitionUsd: 26800,
      image: "assets/images/hero_australia.png",
      tags: ["Tech Precinct", "Sydney Tech Central", "High Employability", "CRICOS: 00099F"],
      programs: ["Cyber Security", "Data Science & AI", "Games Development", "Design & Architecture"],
      sem1Deadline: "2026-12-15",
      sem2Deadline: "2026-06-15",
      requirements: [
        "ATAR equivalent 72+",
        "IELTS 6.5 (writing 6.0)",
        "Genuine Student (GS) assessment",
        "OSHC Coverage"
      ],
      description: "Located right in Sydney's innovative Tech Central precinct, UTS delivers hands-on industry practice, state-of-the-art Frank Gehry architecture, and strong startup accelerators."
    },
    {
      id: "rmit",
      name: "RMIT University",
      shortName: "RMIT",
      country: "Australia",
      state: "Victoria",
      city: "Melbourne, VIC",
      cricos: "00122A",
      institutionType: "University",
      isGo8: false,
      worldRank: 123,
      acceptanceRate: 82.0,
      minGpa: 3.0,
      minSat: 1180,
      minIelts: 6.5,
      minPte: 58,
      atarEquivalent: 68,
      tuitionAud: 37500,
      tuitionUsd: 24500,
      image: "assets/images/campus_sydney.png",
      tags: ["Design & Innovation", "Melbourne City Campus", "Work Integrated Learning", "CRICOS: 00122A"],
      programs: ["Information Technology", "Digital Media & Design", "Aviation", "Software Engineering"],
      sem1Deadline: "2026-12-20",
      sem2Deadline: "2026-06-20",
      requirements: [
        "High School Certificate (ATAR 68 equivalent)",
        "IELTS 6.5 overall",
        "Portfolio (for Design programs only)",
        "Subclass 500 GS Verification"
      ],
      description: "A global university of technology, design, and enterprise based in central Melbourne, famous for industry placements and creative technological innovation."
    },
    {
      id: "uoa",
      name: "The University of Auckland",
      shortName: "UoA",
      country: "New Zealand",
      state: "Auckland",
      city: "Auckland, NZ",
      cricos: "N/A",
      institutionType: "University",
      isGo8: false,
      worldRank: 68,
      acceptanceRate: 45.0,
      minGpa: 3.2,
      minSat: 1250,
      minIelts: 6.0,
      minPte: 50,
      atarEquivalent: 75,
      tuitionAud: 35000,
      tuitionUsd: 23000,
      image: "assets/images/campus_sydney.png",
      tags: ["Rank #1 in NZ", "Research Hub"],
      programs: ["Engineering", "Business", "Medicine"],
      sem1Deadline: "2026-12-08",
      sem2Deadline: "2026-07-04",
      requirements: ["High School Diploma", "IELTS 6.0"],
      description: "New Zealand's highest ranked university, located in the heart of Auckland."
    },
    {
      id: "otago",
      name: "University of Otago",
      shortName: "Otago",
      country: "New Zealand",
      state: "Otago",
      city: "Dunedin, NZ",
      cricos: "N/A",
      institutionType: "University",
      isGo8: false,
      worldRank: 206,
      acceptanceRate: 58.0,
      minGpa: 3.0,
      minSat: 1180,
      minIelts: 6.0,
      minPte: 50,
      atarEquivalent: 70,
      tuitionAud: 32000,
      tuitionUsd: 21000,
      image: "assets/images/hero_australia.png",
      tags: ["Oldest in NZ", "Student City"],
      programs: ["Health Sciences", "Humanities", "Dentistry"],
      sem1Deadline: "2026-12-10",
      sem2Deadline: "2026-06-25",
      requirements: ["High School Diploma", "IELTS 6.0"],
      description: "New Zealand's oldest university, known for its vibrant student lifestyle and health sciences."
    },
    {
      id: "ilsc",
      name: "ILSC Language Schools",
      shortName: "ILSC",
      country: "Australia",
      state: "New South Wales",
      city: "Sydney, NSW",
      cricos: "02137M",
      institutionType: "Language Institute",
      isGo8: false,
      worldRank: 999,
      acceptanceRate: 95.0,
      minGpa: 0,
      minSat: 0,
      minIelts: 0,
      minPte: 0,
      atarEquivalent: 0,
      tuitionAud: 15000,
      tuitionUsd: 10000,
      image: "assets/images/hero_australia.png",
      tags: ["ELICOS", "English Courses"],
      programs: ["General English", "IELTS Mastery", "Cambridge Preparation"],
      sem1Deadline: "Rolling",
      sem2Deadline: "Rolling",
      requirements: ["No minimum GPA", "Passport"],
      description: "Leading language institute offering dynamic English courses and IELTS mastery programs."
    },
    {
      id: "kaplan-nz",
      name: "Kaplan International Languages",
      shortName: "Kaplan NZ",
      country: "New Zealand",
      state: "Auckland",
      city: "Auckland, NZ",
      cricos: "N/A",
      institutionType: "Language Institute",
      isGo8: false,
      worldRank: 999,
      acceptanceRate: 98.0,
      minGpa: 0,
      minSat: 0,
      minIelts: 0,
      minPte: 0,
      atarEquivalent: 0,
      tuitionAud: 14000,
      tuitionUsd: 9000,
      image: "assets/images/campus_sydney.png",
      tags: ["English New Zealand", "Pathways"],
      programs: ["Intensive English", "Academic English", "Exam Prep"],
      sem1Deadline: "Rolling",
      sem2Deadline: "Rolling",
      requirements: ["No minimum GPA", "Passport"],
      description: "Kaplan provides immersive English language courses in beautiful Auckland, with university pathway options."
    }
  ],

  scholarships: [
    {
      id: "sch-aus-awards",
      name: "Australia Awards Scholarships",
      university: "Participating Australian Universities (Go8 & National)",
      country: "Australia",
      coverage: "Full Tuition + Airfare + Living Allowance (AUD $30k/yr) + OSHC",
      type: "Government Full Ride",
      deadline: "2026-04-30",
      eligibility: "High-achieving applicants from partner countries in Asia-Pacific, Latin America, and Africa demonstrating leadership.",
      description: "Prestigious Australian Government awards providing full tuition, return air travel, establishment allowance, and full health cover."
    },
    {
      id: "sch-melb-undergrad",
      name: "Melbourne International Undergraduate Scholarship",
      university: "The University of Melbourne",
      country: "Australia",
      coverage: "100% Tuition Fee Remission (or AUD $10,000 allowance)",
      type: "Merit-Based",
      deadline: "2026-11-30",
      eligibility: "Top international high school graduates applying for undergraduate study at UniMelb.",
      description: "Awarded automatically to high-achieving international students based on ATAR or IB academic merit."
    },
    {
      id: "sch-usyd-achievers",
      name: "Sydney Achievers International Scholarship",
      university: "The University of Sydney",
      country: "Australia",
      coverage: "AUD $10,000 to $20,000 per year",
      type: "Merit-Based",
      deadline: "2026-12-15",
      eligibility: "High performing international students commencing undergraduate degrees at Sydney University.",
      description: "Recognizes exceptional academic performance among incoming international undergraduates."
    },
    {
      id: "sch-unsw-award",
      name: "UNSW International Award",
      university: "UNSW Sydney",
      country: "Australia",
      coverage: "$15,000 per year towards tuition fees",
      type: "Merit & Leadership",
      deadline: "2026-11-30",
      eligibility: "International students commencing full-time coursework degrees at UNSW Sydney.",
      description: "Offers financial support to high-caliber international students undertaking undergraduate study."
    }
  ]
};
